[package]
name = "request"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
aws-sdk-bedrockruntime = "1.91"
aws-smithy-types = "1.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
