[package]
name = "anthropic-response"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-bedrockruntime = "1.126.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
