host = "0.0.0.0"
port = 3000

inference_profile_prefixes = ["us.", "global."]

anthropic_beta_whitelist = ["adaptive-thinking-2026-01-28", "claude-code-20250219", "context-1m-2025-08-07", "effort-2025-11-24", "interleaved-thinking-2025-05-14", "structured-outputs-2025-12-15"]
