[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-stream = "0.3.6"
async-trait = "0.1.88"
aws-config = "1.8.3"
aws-sdk-bedrockruntime = "1.99.0"
axum = "0.8.4"
chrono = "0.4.41"
futures = "0.3.31"
request = { path = "../request" }
uuid = { version = "1.17.0", features = ["v4"] }
response = { path = "../response" }
serde_json = "1.0.141"
tracing = "0.1.41"
reqwest = "0.12.22"
reqwest-streams = { version = "0.10.0", features = ["json"] }
