[package]
name = "anthropic-request"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aws-sdk-bedrockruntime = "1.121"
aws-smithy-types = "1.3"
base64 = "0.22"
common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
