[package]
name = "anthropic-request"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
aws-sdk-bedrockruntime = "1.122.0"
aws-smithy-types = "1.3.6"
common = { path = "../common" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
